@host = https://localhost:7102

### 시나리오 생성
POST {{host}}/scenarios
Content-Type: application/json

{
    "name": "My Classification Model",
    "command": "classification",
    "tags": ["customer-data", "classification", "prototype"]
}

### 시나리오 검색
GET {{host}}/scenarios

### 시나리오 수정
PUT {{host}}/scenarios/{scenarioId}
Content-Type: application/json

{
    "name": "Updated Classification Model",
    "command": "classification",
    "tags": ["customer-data", "production"]
}

### 학습 데이터 업로드
POST {{host}}/scenarios/{scenarioId}/data/Train
Content-Type: multipart/form-data

[파일 데이터]

### 테스트 데이터 업로드
POST {{host}}/scenarios/{scenarioId}/data/Test
Content-Type: multipart/form-data

[파일 데이터]

### 시나리오 정보 조회
GET {{host}}/scenarios/{scenarioId}

### 학습 실행
POST {{host}}/scenarios/{scenarioId}/train

### 예측 실행
POST {{host}}/scenarios/{scenarioId}/predict